config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'member', controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope :admin, as: :admin, path: '/admin' do
    root 'admin#index'
  end

  namespace :admin do
    resources :posts
    resources :pages
    resources :categories
    resources :tags
    resources :comments
    resources :media
  end

  root 'home#index'
  get '/:id', to: 'home#post_or_page', as: :post_or_page

  post '/:id/comment', to: 'home#post_comment', as: :post_comment
  post '/:id/reply_comment/:comment_id', to: 'home#post_comment_reply', as: :post_comment_reply

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true
  validates :slug, presence: true, format: { with: /\A[a-zA-Z0-9_-]+\Z/ }

  before_validation :generate_slug

  private

  def generate_slug
    return if name.blank?

    self.slug = name.parameterize if slug.blank?
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  scope :in_post, lambda { |post_id|
    where(commentable_id: post_id).order('created_at DESC').limit(10)
  }
end

app/models/medium.rb
class Medium < ApplicationRecord
  mount_uploader :file, MediaUploader
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, presence: true
  validates :slug, presence: true, format: { with: /\A[a-zA-Z0-9_-]+\Z/ }

  before_validation :generate_slug

  private

  def generate_slug
    return if title.blank?

    self.slug = title.parameterize if slug.blank?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :post_categories
  has_many :categories, through: :post_categories, dependent: :destroy

  has_many :post_tags
  has_many :tags, through: :post_tags, dependent: :destroy

  has_many :comments, as: :commentable

  validates :title, presence: true
  validates :slug, presence: true, format: { with: /\A[a-zA-Z0-9_-]+\Z/ }
  validates :categories, presence: true

  before_validation :generate_slug

  mount_uploader :image, MediaUploader

  private

  def generate_slug
    return if title.blank?

    self.slug = title.parameterize if slug.blank?
  end
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category

  validates :category_id, uniqueness: { scope: :post_id }
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :tag_id, uniqueness: { scope: :post_id }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags

  validates :name, presence: true
  validates :slug, presence: true, format: { with: /\A[a-zA-Z0-9_-]+\Z/ }

  before_validation :generate_slug

  private

  def generate_slug
    return if name.blank?

    self.slug = name.parameterize if slug.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  devise :omniauthable, omniauth_providers: %i[google_oauth2 facebook twitter]

  validates :username,
            presence: true,
            length: { minimum: 5, maximum: 128 },
            format: { with: /\A[a-zA-Z0-9_]+\Z/ }

  def self.from_omniauth(auth)
    where(provider: auth.provider,
          uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.username = user.name.parameterize(separator: '_')[0..128]
      user.skip_confirmation!
    end
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < AdminController
  rescue_from ActiveRecord::InvalidForeignKey, with: :cannot_delete
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def index
    render :index, locals: { tags: Tag.all }
  end

  def show
    @tag = current_tag
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.create tag_params
    return render :new unless @tag.valid?

    redirect_to admin_tags_path
  end

  def edit
    @tag = current_tag
  end

  def update
    @tag = current_tag

    if @tag.update tag_params
      redirect_to admin_tags_path
    else
      render :edit
    end
  end

  def destroy
    tag = current_tag
    tag.destroy
    redirect_to admin_tags_path,
      notice: "Delete #{tag.name} is success"
  end

  private

  def current_tag
    @current_tag ||= Tag.find params[:id]
  end

  def cannot_delete
    redirect_to admin_tags_path, notice: 'errors'
  end

  def record_not_found
    redirect_to admin_tags_path, notice: 'Tag not found'
  end

  def tag_params
    params.require(:tag).permit(:name, :slug, :description)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin_user

  def index
  end

  private

  def authenticate_admin_user
    return if user_signed_in? && current_user&.isadmin

    not_found
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_user_location!, if: :storable_location?

  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  rescue_from ActionController::RoutingError, with: :not_found
  rescue_from ActionController::UnknownFormat, with: :not_found
  rescue_from ActionController::InvalidAuthenticityToken, with: :invalid_token

  protect_from_forgery with: :exception, prepend: true

  def not_found
    respond_to do |format|
      format.html { render 'not_found', layout: 'application', status: :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end

  protected

  def configure_permitted_parameters
    attributes = [:name, :username]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

  private

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    store_location_for :user, request.fullpath
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    posts = Post.where(published: true).order(:created_at)
    render :index, locals: { posts: posts }
  end

  def post_or_page
    @page = current_page
    return render 'page' if @page.present?

    @post = current_post
    render 'post'
  end

  def post_comment
    comment_params = params.require(:comment).permit(:body)
    comment_params.merge! user_id: current_user.id

    @post = current_post
    @post.comments.create comment_params

    redirect_to post_or_page_path
  end

  private

  def current_post
    @current_post ||= Post.find_by! slug: params[:id], published: true
  end

  def current_page
    @current_page ||= Page.find_by slug: params[:id]
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '')
    ENV['SITENAME'] = 'Narablog' unless ENV['SITENAME'].present?

    title = sitename = ENV['SITENAME']
    title = "#{sitename} - #{page_title}" if page_title.present?
    content_for :title, title
  end
end

class String
  def to_html
    Kramdown::Document.new(self, input: 'GFM').to_html
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/index.html.slim
h1
  | Lalala

app/views/admin/pages/_form.html.slim
= simple_form_for [:admin, @page] do |f|
  .field
    = f.label :title
    .control
      = f.input_field :title, class: 'input'
    = f.full_error :title

  .field
    = f.label :slug
    .control
      = f.input_field :slug, class: 'input'
    = f.full_error :slug

  .field
    = f.label :body
    .control
      = f.text_area :body, class: 'textarea'

  .field
    .control
      = f.button :submit, class: 'is-link'

app/views/admin/pages/create.html.slim
h1 Admin::Pages#create
p Find me in app/views/admin/pages/create.html.slim

app/views/admin/pages/destroy.html.slim
h1 Admin::Pages#destroy
p Find me in app/views/admin/pages/destroy.html.slim

app/views/admin/pages/edit.html.slim
= render partial: 'form'

app/views/admin/pages/index.html.slim
.admin_items
  .header
    h1.title
      | Static Pages
    .new_page
      = link_to new_admin_page_path,
                class: 'button is-light is-small' do
                span.icon
                  i.mdi.mdi-pencil-plus
                span
                  | New
  .table-container
    table.table.is-striped
      thead
        th
          | Title
        th
          | Created at
      tbody
        - pages.each do |page|
          tr
            td
              = link_to truncate(page.title, length: 50, separator: ''),
                        edit_admin_page_path(page)
              span.action
                ul
                  li
                    = link_to edit_admin_page_path(page) do
                      span.icon
                        i.mdi.mdi-circle-edit-outline
                      span
                        | Edit
                  li
                    = link_to  admin_page_path(page),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } do
                      span.icon
                        i.mdi.mdi-delete
                      span
                        | Delete
                  li
                    = link_to admin_page_path(page) do
                      span.icon
                        i.mdi.mdi-open-in-new
                      span
                        | View

            td = page.created_at.strftime('%b %d, %Y')

app/views/admin/pages/new.html.slim
= render partial: 'form'

app/views/admin/pages/show.html.slim
h1 Admin::Pages#show
p Find me in app/views/admin/pages/show.html.slim

app/views/admin/pages/update.html.slim
h1 Admin::Pages#update
p Find me in app/views/admin/pages/update.html.slim

app/views/layouts/admin/_breadcrumb.html.slim
- paths = request.path.split('/').drop(1)

nav.breadcrumb.has-arrow-separator[aria-label="breadcrumbs"]
  ul
    - paths.each_with_index do |path, index|
      - if path != paths.last
        - req_path = request.path.split('/').drop(1).shift(index+1)
        li = link_to path.capitalize, "/#{req_path.join('/')}"
      - else
          li.is-active
            a[href="#" aria-current="page"]
              = path.capitalize

app/views/layouts/admin/_navbar.html.slim
nav.navbar.is-dark[role="navigation" aria-label="main navigation"]
  .navbar-brand
    a.navbar-burger[role="button" aria-label="menu" aria-expanded="false" data-target="naranavbar"]
      span[aria-hidden="true"]
      span[aria-hidden="true"]
      span[aria-hidden="true"]

  #naranavbar.navbar-menu
    .navbar-end
      .navbar-item.has-dropdown.is-hoverable
        a.navbar-link
          = current_user.name
          .navbar-dropdown.is-right
            a.navbar-item
             | User Profile
            hr.navbar-divider
            = link_to 'Logout',
                      destroy_user_session_path,
                      class: 'navbar-item',
                      method: :delete

app/views/layouts/admin/_sidebar.html.slim
.sidebar
  .sidebar__title.has-background-black
    span
      | Narablog
  .sidebar__menu
    ul
      li
        = link_to admin_root_path, class: current_page?(admin_root_path) ? 'active' : '' do
          span.icon
            i.mdi.mdi-desktop-mac
          span.title
            | Dashboard
      li
        = link_to admin_posts_path, class:  params[:controller] == 'admin/posts' ? 'active' : '' do
          span.icon
            i.mdi.mdi-pencil
          span.title
            | Posts
      li
        = link_to admin_pages_path, class:  params[:controller] == 'admin/pages' ? 'active' : '' do
          span.icon
            i.mdi.mdi-note-outline
          span.title
            | Static Pages
      li
        = link_to admin_categories_path, class:  params[:controller] == 'admin/categories' ? 'active' : '' do
          span.icon
            i.mdi.mdi-tag-text-outline
          span.title
            | Categories
      li
        = link_to admin_tags_path, class: params[:controller] == 'admin/tags' ? 'active' : '' do
          span.icon
            i.mdi.mdi-tag-multiple
          span.title
            | Tags
      li
        = link_to admin_comments_path, class: params[:controller] == 'admin/comments' ? 'active' : '' do
          span.icon
            i.mdi.mdi-comment
          span.title
            | Comments
      li
        = link_to admin_media_path, class: params[:controller] == 'admin/media' ? 'active' : '' do
          span.icon
            i.mdi.mdi-account
          span.title
            | Media