config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'member', controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope :admin, as: :admin, path: '/admin' do
    root 'admin#index'
  end

  namespace :admin do
    resources :posts
    resources :pages
    resources :categories
    resources :tags
    resources :comments
    resources :media
  end

  root 'home#index'
  get '/:id', to: 'home#post_or_page', as: :post_or_page

  post '/:id/comment', to: 'home#post_comment', as: :post_comment
  post '/:id/reply_comment/:comment_id', to: 'home#post_comment_reply', as: :post_comment_reply

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    posts = Post.where(published: true).order(:created_at)
    render :index, locals: { posts: posts }
  end

  def post_or_page
    @page = current_page
    return render 'page' if @page.present?

    @post = current_post
    render 'post'
  end

  def post_comment
    comment_params = params.require(:comment).permit(:body)
    comment_params.merge! user_id: current_user.id

    @post = current_post
    @post.comments.create comment_params

    redirect_to post_or_page_path
  end

  private

  def current_post
    @current_post ||= Post.find_by! slug: params[:id], published: true
  end

  def current_page
    @current_page ||= Page.find_by slug: params[:id]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_sidebar.html.slim
article.message.has-shadow.is-dark
  .message-header.is-size-5
    p
      | Artikel Lainnya

  .message-body
    | Lorep ipsum

app/views/home/_wave.html.slim
svg.wave[style="height: 2.5rem" preserveaspectratio="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewbox="0 0 1920 75"]
  defs
    style
      |  .a { fill: none; } .b { clip-path: url(#a); } .c, .d { fill: #ffffff; } .d { opacity: 0.5; isolation: isolate; }
    clippath#a
      rect.a[width="1920" height="75"]
  g.b
    path.c[d="M1963,327H-105V65A2647.49,2647.49,0,0,1,431,19c217.7,3.5,239.6,30.8,470,36,297.3,6.7,367.5-36.2,642-28a2511.41,2511.41,0,0,1,420,48"]
  g.b
    path.d[d="M-127,404H1963V44c-140.1-28-343.3-46.7-566,22-75.5,23.3-118.5,45.9-162,64-48.6,20.2-404.7,128-784,0C355.2,97.7,341.6,78.3,235,50,86.6,10.6-41.8,6.9-127,10"]
  g.b
    path.d[d="M1979,462-155,446V106C251.8,20.2,576.6,15.9,805,30c167.4,10.3,322.3,32.9,680,56,207,13.4,378,20.3,494,24"]
  g.b
    path.d[d="M1998,484H-243V100c445.8,26.8,794.2-4.1,1035-39,141-20.4,231.1-40.1,378-45,349.6-11.6,636.7,73.8,828,150"]

app/views/home/index.html.slim
- sitename = ENV['SITENAME']
- sitedesc = ENV['SITE_DESCRIPTION']
- site_logo = image_pack_tag 'arsipkode-circle.png'
- content_for :metadata do
  meta[property="title" content=(sitename)]
  meta[property="description" content=(strip_tags(sitedesc))]
  meta[property="og:title" content=(sitename)]
  meta[property="og:type" content="website"]
  meta[property="og:url" content=(request.original_url)]
  meta[property="og:image" content=(request.base_url + site_logo.gsub(/^(\<img\ssrc=\")|\"\s\/\>/, ''))]
  meta[property="og:description" content=(strip_tags(sitedesc)[0..119])]
  meta[property="og:locale" content="id_ID"]
  meta[property="og:site_name" content=(sitename)]

section.hero.is-link.is-bold
  .hero-body
    .container.is-fluid
      - if sitename.present?
        h1.title.is-uppercase.is-size-1.has-text-weight-bold
          = sitename.split[0]
          - if sitename.split.count > 1
            = ' '
            span.has-bg-tag
              = sitename.split.drop(1).join(' ')

        h2.subtitle.mt-1
          = sanitize(ENV['SITE_DESCRIPTION'])

  = render partial: 'wave'

section.section.is-size-5
  .container.is-fluid
    .columns
      .column.is-8
        - posts.each do |post|
          .post-header
            h1.title.mb-0
              = link_to post.title, post_or_page_path(post.slug)
            h2.subtitle.is-inline.mr-4
              = post.created_at.to_date.to_formatted_s(:long)
            .tags.is-inline
              - tag_colors = ['is-warning', 'is-danger', 'is-dark', 'is-primary']
              - post.tags.each do |tag|
                span class=("tag #{tag_colors.sample}")
                    = tag.name
          .post-content
            = sanitize(strip_tags(post.body.to_html).truncate(300, separator: ' '))
      .column.is-4
         = render partial: 'sidebar'

app/views/home/page.html.slim
- page_title @page.title
- content_for :metadata do
  meta[property="og:title" content=(@page.title)]
  meta[property="og:type" content="website"]
  meta[property="og:url" content=(request.original_url)]
  meta[property="og:description" content=(strip_tags(@page.body.to_html)[0..119])]
  meta[property="og:locale" content="id_ID"]
  meta[property="og:site_name" content=(ENV['SITENAME'])]
  meta[property="article:published_time" content=(@page.created_at.iso8601)]
  meta[property="article:modified_time" content=(@page.updated_at.iso8601)]
  meta[property="article:section" content="page"]

section.hero.is-link.is-bold
  .hero-body
    .container.is-fluid
      h1.title.is-size-1
        = @page.title
      h2.subtitle
        = @page.created_at.to_date.to_formatted_s(:long)

  = render partial: 'wave'

.container.is-fluid
  section.section
    article
      .content.is-size-5
        = sanitize(@page.body.to_html)

app/views/home/post.html.slim
- page_title @post.title
- content_for :metadata do
  meta[property="og:title" content=(@post.title)]
  meta[property="og:type" content="website"]
  meta[property="og:url" content=(request.original_url)]
  - if @post.image.present?
    meta[property="og:image" content=(request.base_url + @post.image.url)]
  - else
    - site_logo = image_pack_tag 'arsipkode-circle.png'
    meta[property="og:image" content=(request.base_url + site_logo.gsub(/^(\<img\ssrc=\")|\"\s\/\>/, ''))]
  meta[property="og:description" content=(strip_tags(@post.body.to_html)[0..119])]
  meta[property="og:locale" content="id_ID"]
  meta[property="og:site_name" content=(ENV['SITENAME'])]
  meta[property="article:published_time" content=(@post.created_at.iso8601)]
  meta[property="article:modified_time" content=(@post.updated_at.iso8601)]
  meta[property="article:author" content=(@post.user.name)]
  - @post.categories.each do |category|
    meta[property="article:section" content=(category.name)]
  - @post.tags.each do |tag|
    meta[property="article:tag" content=(tag.name)]

section.hero.is-link.is-bold
  .hero-body
    .container.is-fluid
      h1.title.is-size-1
        = @post.title
      h2.subtitle
        = @post.created_at.to_date.to_formatted_s(:long)
        = " - Ditulis oleh #{@post.user.name.capitalize}"
      .tags
        - tag_colors = ['is-warning', 'is-danger', 'is-dark', 'is-primary']
        - @post.tags.each do |tag|
          span class=("tag #{tag_colors.sample}")
              = tag.name
  = render partial: 'wave'

.container.is-fluid
  section.section
    .columns
      .column
        article
          .content.is-size-5
            = sanitize(@post.body.to_html)

            hr
            h1.title
              | Comments

            article.media
              .media-content
                = simple_form_for Comment.new, url: post_comment_path, method: :post do |f|
                  .field
                    .control
                      = f.text_area :body, class: 'textarea'
                    = f.hint 'Support markdown formatting'

                  - if user_signed_in?
                      .field
                        .control
                          = f.button :submit, 'Post Comment', class: 'is-link'
                  - else
                      .field
                        .control
                           p.has-text-danger
                             | Please sign in to post your comment:
                           = link_to 'Sign in', user_session_path,  class: 'button is-primary'


            - Comment.in_post(@post).each do |comment|
                article.media
                  figure.media-left
                    p.image.is-64x64
                      img[src="https://bulma.io/images/placeholders/128x128.png"]
                  .media-content
                    .content
                      strong = comment.user.name
                      = sanitize(comment.body.to_html)
      .column.is-4
        = render partial: 'sidebar'