config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'member', controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope :admin, as: :admin, path: '/admin' do
    root 'admin#index'
  end

  namespace :admin do
    resources :posts
    resources :pages
    resources :categories
    resources :tags
    resources :comments
    resources :media
  end

  root 'home#index'
  get '/:id', to: 'home#post_or_page', as: :post_or_page

  post '/:id/comment', to: 'home#post_comment', as: :post_comment
  post '/:id/reply_comment/:comment_id', to: 'home#post_comment_reply', as: :post_comment_reply

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags
  has_many :posts, through: :post_tags

  validates :name, presence: true
  validates :slug, presence: true, format: { with: /\A[a-zA-Z0-9_-]+\Z/ }

  before_validation :generate_slug

  private

  def generate_slug
    return if name.blank?

    self.slug = name.parameterize if slug.blank?
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < AdminController
  rescue_from ActiveRecord::InvalidForeignKey, with: :cannot_delete
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def index
    render :index, locals: { tags: Tag.all }
  end

  def show
    @tag = current_tag
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.create tag_params
    return render :new unless @tag.valid?

    redirect_to admin_tags_path
  end

  def edit
    @tag = current_tag
  end

  def update
    @tag = current_tag

    if @tag.update tag_params
      redirect_to admin_tags_path
    else
      render :edit
    end
  end

  def destroy
    tag = current_tag
    tag.destroy
    redirect_to admin_tags_path,
      notice: "Delete #{tag.name} is success"
  end

  private

  def current_tag
    @current_tag ||= Tag.find params[:id]
  end

  def cannot_delete
    redirect_to admin_tags_path, notice: 'errors'
  end

  def record_not_found
    redirect_to admin_tags_path, notice: 'Tag not found'
  end

  def tag_params
    params.require(:tag).permit(:name, :slug, :description)
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/_form.html.slim
= simple_form_for [:admin, @tag] do |f|
  .field
    = f.label :name
    .control
      = f.input_field :name, class: 'input'
    = f.full_error :name

  .field
    = f.label :slug
    .control
      = f.input_field :slug, class: 'input'
    = f.full_error :slug

  .field
    = f.label :description
    .control
      = f.text_area :description, class: 'textarea'

  .field
    .control
      = f.button :submit, class: 'is-link'

app/views/admin/tags/create.html.slim
h1 Admin::Tags#create
p Find me in app/views/admin/tags/create.html.slim

app/views/admin/tags/destroy.html.slim
h1 Admin::Tags#destroy
p Find me in app/views/admin/tags/destroy.html.slim

app/views/admin/tags/index.html.slim
.admin_items
  .header
    h1.title
      | Tags
    .new_post
      = link_to new_admin_tag_path,
                class: 'button is-light is-small' do
                span.icon
                  i.mdi.mdi-pencil-plus
                span
                  | New
  .table-container
    table.table.is-striped
      thead
        th
          | Name
        th
          | Posts
        th
          | Created at
      tbody
        - tags.each do |tag|
          tr
            td
              = link_to truncate(tag.name, length: 50, separator: ''),
                        edit_admin_tag_path(tag)
              span.action
                ul
                  li
                    = link_to edit_admin_tag_path(tag) do
                      span.icon
                        i.mdi.mdi-circle-edit-outline
                      span
                        | Edit
                  li
                    = link_to  admin_tag_path(tag),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } do
                      span.icon
                        i.mdi.mdi-delete
                      span
                        | Delete
                  li
                    = link_to admin_tag_path(tag) do
                      span.icon
                        i.mdi.mdi-open-in-new
                      span
                        | View

            td = tag.posts.count
            td = tag.created_at.strftime('%b %d, %Y')

app/views/admin/tags/show.html.slim
h1 Admin::Tags#show
p Find me in app/views/admin/tags/show.html.slim

app/views/admin/tags/update.html.slim
h1 Admin::Tags#update
p Find me in app/views/admin/tags/update.html.slim