config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'member', controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  scope :admin, as: :admin, path: '/admin' do
    root 'admin#index'
  end

  namespace :admin do
    resources :posts
    resources :pages
    resources :categories
    resources :tags
    resources :comments
    resources :media
  end

  root 'home#index'
  get '/:id', to: 'home#post_or_page', as: :post_or_page

  post '/:id/comment', to: 'home#post_comment', as: :post_comment
  post '/:id/reply_comment/:comment_id', to: 'home#post_comment_reply', as: :post_comment_reply

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true
  validates :slug, presence: true, format: { with: /\A[a-zA-Z0-9_-]+\Z/ }

  before_validation :generate_slug

  private

  def generate_slug
    return if name.blank?

    self.slug = name.parameterize if slug.blank?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  rescue_from ActiveRecord::InvalidForeignKey, with: :cannot_delete
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def index
    render :index, locals: { categories: Category.all }
  end

  def show
    @category = current_category
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create category_params
    return render :new unless @category.valid?

    redirect_to admin_categories_path
  end

  def edit
    @category = current_category
  end

  def update
    @category = current_category

    if @category.update category_params
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    category = current_category
    category.destroy
    redirect_to admin_categories_path,
      notice: "Delete #{category.name} is success"
  end

  private

  def current_category
    @current_category ||= Category.find params[:id]
  end

  def cannot_delete
    redirect_to admin_categories_path, notice: 'errors'
  end

  def record_not_found
    redirect_to admin_categories_path, notice: 'Category not found'
  end

  def category_params
    params.require(:category).permit(:name, :slug, :description)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form.html.slim
= simple_form_for [:admin, @category] do |f|
  .field
    = f.label :name
    .control
      = f.input_field :name, class: 'input'
    = f.full_error :name

  .field
    = f.label :slug
    .control
      = f.input_field :slug, class: 'input'
    = f.full_error :slug

  .field
    = f.label :description
    .control
      = f.text_area :description, class: 'textarea'

  .field
    .control
      = f.button :submit, class: 'is-link'

app/views/admin/categories/create.html.slim
h1 Admin::Categories#create
p Find me in app/views/admin/categories/create.html.slim

app/views/admin/categories/destroy.html.slim
h1 Admin::Categories#destroy
p Find me in app/views/admin/categories/destroy.html.slim

app/views/admin/categories/index.html.slim
.admin_items
  .header
    h1.title
      | Categories
    .new_post
      = link_to new_admin_category_path,
                class: 'button is-light is-small' do
                span.icon
                  i.mdi.mdi-pencil-plus
                span
                  | New
  .table-container
    table.table.is-striped
      thead
        th
          | Name
        th
          | Posts
        th
          | Created at
      tbody
        - categories.each do |category|
          tr
            td
              = link_to truncate(category.name, length: 50, separator: ''),
                        edit_admin_category_path(category)
              span.action
                ul
                  li
                    = link_to edit_admin_category_path(category) do
                      span.icon
                        i.mdi.mdi-circle-edit-outline
                      span
                        | Edit
                  li
                    = link_to  admin_category_path(category),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } do
                      span.icon
                        i.mdi.mdi-delete
                      span
                        | Delete
                  li
                    = link_to admin_category_path(category) do
                      span.icon
                        i.mdi.mdi-open-in-new
                      span
                        | View

            td = category.posts.count
            td = category.created_at.strftime('%b %d, %Y')

app/views/admin/categories/show.html.slim
h1.title
  = @category.name
p
  = "Slug: /#{@category.slug}/"
p
  = "Posts: #{@category.posts.count}"

app/views/admin/categories/update.html.slim
h1 Admin::Categories#update
p Find me in app/views/admin/categories/update.html.slim